export const FORM_TEXTS = {
  password: "demopassword",
  interestedQuestion: "Interested in Playwright?",
  invalidEmail: "invalidemail",
  invalidPhone: "12345",
  sampleEmail: "sample@example.com",
  oliverEmail: "oliver@example.com",
  usPhoneNo: "4155552671",
  emailFieldLabel: "Email address*",
  fullNameFieldLabel: "Full name*",
  phoneNumberFieldLabel: "Phone number*",
  reqEmail: "Email address is required",
  reqFirstName: "First name is required",
  reqLastName: "Last name is required",
  reqPhone: "Phone number is invalid",
  usNumberStart: "US numbers cannot start with",
  emailInvalid: "Email address is invalid",
  firstName: "Oliver",
  lastName: "Smith",
  fullName: "Oliver Smith",
  validPhoneNo: "🇺🇸+1 415 555",
  optionsUpto10: "Option 5, Option 6, Option 7, Option 8, Option 9, Option 10",
  multipleChoice: "Multiple Choice",
  singleChoice: "Single Choice",
  yes: "Yes",
  no: "No",
  show: "Show",
  emailAddress: "Email address",
  contains: "contains",
};
